<a href="https://colab.research.google.com/github/paulapalma1/ejercicios/blob/main/Ejercicios_prueba_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

8 junio actividad subir nota (voluntario: grupal - máximo 3)
15 junio prueba (debe estar completado cisco
22 nota final de semestre
29 pruebas pendientes
1a o 2a semana julio examen 
8 agosto 2do semestre 


arreglos

In [ ]:
import numpy as np
arreglo=np.array([1,2,3,4,5])

#arreglo

print(arreglo)

[1 2 3 4 5]


In [ ]:
arreglo.ndim


1

In [ ]:
len(arreglo)

5

In [ ]:
arreglo.shape

(5,)

In [ ]:
arreglo[1:4]

array([2, 3, 4])

In [ ]:
arreglo[:]

array([1, 2, 3, 4, 5])

In [ ]:
arreglo[::2]


array([1, 3, 5])

In [ ]:
arreglo[-3]

3

In [ ]:
for i in range (len(arreglo)):
  print(arreglo[i])

1
2
3
4
5


In [ ]:
import numpy as np
import random as rd
arreglo1=np.zeros(10,dtype=int) #inicializa el arreglo con zeros 
print(arreglo1)

for i in range(10):
  arreglo1[i]=rd.randint(0,100)

print(arreglo1)

arreglo2=arreglo1.copy()

print("ELEMENTO MAYOR ",arreglo2.max())
print("ELEMENTO MENOR ",arreglo2.min())
print("SUMA ",arreglo2.sum())
print("PROMEDIO ",arreglo2.mean())

print(arreglo2)




[0 0 0 0 0 0 0 0 0 0]
[94 55 43 32 46 28  7 22 15  7]
ELEMENTO MAYOR  94
ELEMENTO MENOR  7
SUMA  349
PROMEDIO  34.9
[94 55 43 32 46 28  7 22 15  7]


In [ ]:
import numpy as np
import random as rd
arregloA=np.zeros(100,dtype=int) #inicializa el arreglo con zeros 
print(arregloA)

for i in range(100):
  arregloA[i]=rd.randint(0,500)

print("\n",arregloA)

arregloA[::2]

max= arregloA.max()
print("\nel mayor de los elementos del arreglo es: ", max)

guardamayor=0
j=0
for i in range(len(arregloA)):
  if arregloA[i]>guardamayor:
    guardamayor=arregloA[i]
    j=i

print("\nla posición (índice) del mayor es: ", j)

min= arregloA.min()
print("\nel menor de los elementos del arreglo es:", min)

arregloB = arregloA[:].copy()

print("\n",arregloB)

arregloC= arregloB*3

print("\n",arregloC)

suma=arregloB.sum()
print("\nla suma de los elementos del arreglo B es:",suma)

promedio=arregloB.mean()
print("\nel promedio de los elementos del arreglo B es:", promedio)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

 [121 215 393 422 406 136 386 459 475 179 284  75 220  93 463 249 245 246
 163 414 226 330 349 251  75 195 321 228  32  87 376 467  41  11 472 436
 325 121 438 457 144  29 170 190 305  65 470 218 373 352 414 344 228 212
 400  76 314 196 113 274 190 298 330 100  46 413 342 124 387 232 231 289
 162 137 286 165 193 237 243  52 168 286 361 278 377 236 295 107 448 495
 348  86 478 267 490 156 271 317 240  47]

el mayor de los elementos del arreglo es:  495

la posición (índice) del mayor es:  89

el menor de los elementos del arreglo es: 11

 [121 215 393 422 406 136 386 459 475 179 284  75 220  93 463 249 245 246
 163 414 226 330 349 251  75 195 321 228  32  87 376 467  41  11 472 436
 325 121 438 457 144  29 170 190 305  65 470 218 373 352 414 344 228 212
 400  76 314 196 113 274 190 298

In [ ]:
import numpy as np
import random as rd
matriz=np.zeros((3,3), dtype=int)
print(matriz)
for f in range(3):
  for c in range(3):
    matriz[f][c]=rd.randint(0,100)

print("\n", matriz)


[[0 0 0]
 [0 0 0]
 [0 0 0]]

 [[51 45 58]
 [ 4 49 49]
 [95  5 52]]


FUNCIONES

In [ ]:
def calculariva(precio):
    iva=precio*0.19
    return iva

def calculodescuento(precio,descuento):
    descuento=precio*descuento/100
    return descuento

def calculoimc(peso,estatura):
    IMC=peso/(estatura**2)
    return IMC

op=3
while op!=4:
    print("***MENU***")
    print("*"*10)
    print("1. Calcular IVA")
    print("1. Descuento")
    print("1. Calcular IMC")
    print("4. SALIR")
    op=int(input("Ingrese su opción: (1:4):"))
    if op==1:
        precio=int(input("Ingrese precio del producto: ")) 
        iva=int(calculariva(precio))
        print("El IVA del producto es: ", iva)
    
    if op==2:
        precio=int(input("Ingrese precio del producto: ")) 
        descuento=int(input("Ingrese el porcentaje de descuento: "))
        valordesc=int(calculodescuento(precio,descuento))
        print("El monto de descuento es: ", valordesc) 
        valorfinal=int(precio-valordesc)
        print("El precio con el descuento aplicado es: ", valorfinal)

    if op==3:
        peso=float(input("Ingrese el peso: "))
        estatura=float(input("Ingrese la estatura: "))
        IMC=calculoimc(peso,estatura)
        print("Su IMC es: ", round(IMC,2))
        if IMC<18.5:
            print("Bajo peso")
        elif IMC<24.9:
            print("peso adecuado")
        elif IMC<29.9:
            print("sobrepeso")
        elif IMC<34.9:
            print("obesidad grado 1")
        elif IMC<39.9:
            print("obesidad grado 2")
        else:
            print("obesidad grado 3")

In [ ]:
print("ejercicios con arreglos")
import numpy as np
import random as rd
'''arreglo1=np.arange(1,4)
print(arreglo1)
arreglo2=arreglo1[:].copy()
print(arreglo2)
arreglo2[0]=100
print(arreglo2)
print(arreglo1)
arreglo1=arreglo1*2
print(arreglo1)'''
arregloA=np.zeros(100, dtype=int) #inicializa el arreglo
print(arregloA)
for i in range(len(arregloA)):
    arregloA[i]=rd.randint(0,500)
print(arregloA)
for i in range(len(arregloA)):
    if arregloA[i]%2==0:
        print(arregloA[i])
        print("la posición es: ", i)
for i in range(len(arregloA)):
    if i%2==0:
        print(arregloA[i])
mayor=arregloA.max()
print("el mayor es:",mayor)